ogp:
  site_name: "逆転教材"
  twitter_site: "@yoshito410kam"
  default_description: "人生逆転サロンの教材です"
  default_twitter_image: "no_image.jpg"
programming:
  rails: "Basic, Git, HTML&CSS, Ruby, Ruby on Rails"
  general: "Movie, Writing, Php, Marketing, Design, Other, Money"
  live: "Salon, Talk, Live"